language: c

sudo: false

matrix:
  include:
    - compiler: ": Lua51-osx"
      env: LUA="lua 5.1"
      os: osx
    - compiler: ": Lua51"
      env: LUA="lua 5.1"
      os: linux
    - compiler: ": Lua52"
      env: LUA="lua 5.2"
      os: linux
    - compiler: ": Lua53"
      env: LUA="lua 5.3"
      os: linux
    - compiler: ": LuaJIT20"
      env: LUA="luajit 2.0"
      os: linux
    - compiler: ": LuaJIT21"
      env: LUA="luajit 2.1"
      os: linux
    - compiler: ": LuaJIT21-osx"
      env: LUA="luajit 2.1"
      os: osx

cache:
  directories:
    - here
    - $HOME/.cache/pip

branches:
  only:
    - master

before_install:
  - export CC=gcc
  - gcc --version
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH=$PATH:~/Library/Python/2.7/bin/; fi
  - pip install --user cpp-coveralls
  - pip install --user hererocks
  - hererocks here -r^ --$LUA
  - source here/bin/activate
  - if [ "$(expr substr $LUA 1 6)" == "luajit" ]; then
      luarocks install ljsyscall;
    fi
  - luarocks show luafilesystem > /dev/null 2>&1 || luarocks install luafilesystem

install:
  - luarocks make rockspecs/lua-path-scm-0.rockspec

before_script:
  - luarocks show luacov > /dev/null 2>&1 || luarocks install luacov
  - luarocks show lunitx > /dev/null 2>&1 || luarocks install lunitx

script:
  - cd test
  - lunit.sh run.lua
  - lua -lluacov test_lfs.lua

after_success:
  - luarocks show lua-curl         > /dev/null 2>&1 || luarocks install lua-curl
  - luarocks show luacov-coveralls > /dev/null 2>&1 || luarocks install luacov-coveralls
  - luacov-coveralls

notifications:
  email:
    on_success: change
    on_failure: always
